import { Course } from "./types";

export const courses: Course[] = [
  {
    slug: "zeichnen-fuer-einsteiger",
    title: "Zeichnen für Einsteiger",
    category: "zeichnen",
    shortDescription: "Grundlagen von Strich, Schraffur und Perspektive mit Faber-Castell-Material.",
    description:
      "In diesem Kurs lernst du die Grundtechniken des Zeichnens kennen: von der Strichführung über Schraffuren bis zur einfachen Perspektive. Alle Materialien von Faber-Castell werden gestellt.",
    durationMinutes: 120,
    price: 59,
    room: "Atelier 1",
    brandPartnerId: "faber-castell",
    imageSrc: "/course-images/faber-castell-zeichnen.jpg",
    level: "Einsteiger",
    maxParticipants: 12,
  },
  {
    slug: "urban-sketching",
    title: "Skizzieren im Park – Urban Sketching",
    category: "zeichnen",
    shortDescription: "Schnelles, lockeres Skizzieren von Alltagsszenen und Architektur.",
    description:
      "Wir ziehen los und skizzieren München: Architektur, Menschen, Straßenszenen. Ein Kurs für alle, die schnell und intuitiv zeichnen lernen wollen.",
    durationMinutes: 90,
    price: 49,
    room: "Treffpunkt Halle / Außenbereich",
    imageSrc: "/course-images/skizze-hand.jpg",
    level: "Alle Level",
    maxParticipants: 10,
  },
  {
    slug: "mercedes-design-sketching",
    title: "Mercedes-Benz Design Lab: Zeichne dein Traumauto",
    category: "zeichnen",
    shortDescription: "Autodesign skizzieren mit einem Designer aus dem Mercedes-Benz Designstudio.",
    description:
      "Ein Designer aus dem Mercedes-Benz Designstudio zeigt dir, wie aus der ersten Linie ein Auto wird: Proportionen, Perspektive, Licht und Schatten. Mit Marker und Bleistift skizzierst du dein eigenes Concept Car – von der Seitenansicht bis zur dynamischen Dreiviertelansicht. Zum Abschluss besprechen wir die Entwürfe gemeinsam, die besten werden in der Halle ausgestellt. Inklusive Getränke und Snacks.",
    durationMinutes: 180,
    price: 119,
    room: "Atelier 1 & 2",
    brandPartnerId: "mercedes-benz",
    imageSrc: "/course-images/mercedes-design.jpg",
    level: "Alle Level",
    maxParticipants: 12,
  },
  {
    slug: "aquarell-grundkurs",
    title: "Aquarellmalerei Grundkurs",
    category: "malen",
    shortDescription: "Farbmischung, Lasuren und Technik mit Faber-Castell-Aquarellfarben.",
    description:
      "Ein Einstieg in die Aquarellmalerei: Farbmischung, nass-in-nass Technik und erste kleine Kompositionen. Material von Faber-Castell inklusive.",
    durationMinutes: 150,
    price: 59,
    room: "Atelier 2",
    brandPartnerId: "faber-castell",
    imageSrc: "/course-images/aquarell-farben.jpg",
    level: "Einsteiger",
    maxParticipants: 10,
  },
  {
    slug: "koffer-kunst-rimowa",
    title: "Koffer-Kunst: Dein RIMOWA, dein Design",
    category: "malen",
    shortDescription: "Gestalte einen echten RIMOWA-Koffer mit deinem eigenen Design.",
    description:
      "In Kooperation mit RIMOWA gestaltest du einen echten Aluminium-Koffer nach deinen eigenen Vorstellungen – von abstrakten Mustern bis zum persönlichen Motiv. Der Koffer geht mit dir nach Hause.",
    durationMinutes: 120,
    price: 119,
    room: "Atelier 1",
    brandPartnerId: "rimowa",
    imageSrc: "/course-images/rimowa-koffer.jpg",
    level: "Alle Level",
    maxParticipants: 8,
  },
  {
    slug: "toepfern-scheibe",
    title: "Töpfern an der Scheibe",
    category: "toepfern",
    shortDescription: "Erste Gefäße an der Töpferscheibe formen.",
    description:
      "Du lernst den Umgang mit der Töpferscheibe und formst deine ersten eigenen Gefäße. Für Einsteiger geeignet, Brennen und Abholung im Anschluss möglich.",
    durationMinutes: 180,
    price: 79,
    room: "Werkraum Keramik",
    imageSrc: "/course-images/bildhauer-atelier.jpg",
    level: "Einsteiger",
    maxParticipants: 8,
  },
  {
    slug: "keramik-handaufbau",
    title: "Keramik-Handaufbau für Anfänger",
    category: "toepfern",
    shortDescription: "Gefäße ganz ohne Scheibe formen – mit Wulst- und Plattentechnik.",
    description:
      "Handaufbau-Techniken wie Wulst- und Plattentechnik eignen sich hervorragend für den Einstieg in die Keramik – ganz ohne Scheibe.",
    durationMinutes: 150,
    price: 69,
    room: "Werkraum Keramik",
    imageSrc: "/course-images/keramik-handaufbau.jpg",
    level: "Einsteiger",
    maxParticipants: 10,
  },
  {
    slug: "sticken-mit-stil",
    title: "Sticken mit Stil",
    category: "sticken",
    shortDescription: "Individuelle Stickmuster auf lululemon-Textilien gestalten.",
    description:
      "Gemeinsam mit lululemon gestaltest du individuelle Stickereien auf hochwertigen Sportbekleidungsstücken – von Monogrammen bis zu kleinen Icons.",
    durationMinutes: 120,
    price: 59,
    room: "Atelier 3",
    brandPartnerId: "lululemon",
    imageSrc: "/course-images/lululemon-sticken.jpg",
    level: "Alle Level",
    maxParticipants: 10,
  },
  {
    slug: "yoga-flow",
    title: "Yoga Flow",
    category: "yoga",
    shortDescription: "Dynamischer Vinyasa-Flow in Kooperation mit lululemon.",
    description:
      "Ein fließender Vinyasa-Flow für Körper und Geist, begleitet von lululemon mit Equipment und Kleidung zum Testen vor Ort.",
    durationMinutes: 75,
    price: 39,
    room: "Bewegungsraum",
    brandPartnerId: "lululemon",
    imageSrc: "/course-images/yoga-panorama.jpg",
    level: "Alle Level",
    maxParticipants: 16,
  },
  {
    slug: "steinhauen-grundlagen",
    title: "Steinhauen Grundlagen mit Profi-Werkzeug",
    category: "steinhauen",
    shortDescription: "Erste Schritte in der Steinbildhauerei mit Hilti-Werkzeug.",
    description:
      "Mit professionellem Hilti-Werkzeug lernst du die Grundlagen der Steinbearbeitung: Materialkunde, Sicherheit und erste einfache Formen.",
    durationMinutes: 180,
    price: 99,
    room: "Werkhalle",
    brandPartnerId: "hilti",
    imageSrc: "/course-images/steinhauen-atelier.jpg",
    level: "Einsteiger",
    maxParticipants: 6,
  },
  {
    slug: "rage-room",
    title: "Rage Room – Stress rauslassen",
    category: "rage-room",
    shortDescription: "Kontrolliert Dinge zertrümmern, um Dampf abzulassen.",
    description:
      "In Schutzausrüstung geht's rein: Geschirr, alte Elektronik und mehr werden mit Schlägern und Stangen zertrümmert. Ein Kurs zum Stressabbau.",
    durationMinutes: 45,
    price: 49,
    room: "Rage Room",
    imageSrc: "/course-images/rage-room.jpg",
    level: "Alle Level",
    maxParticipants: 4,
  },
  {
    slug: "sternekueche-zuhause",
    title: "Kochkurs: Sterneküche für Zuhause",
    category: "kochen",
    shortDescription: "Sterneküche zum Anfassen mit Chef Markus Reiter.",
    description:
      "Gemeinsam mit einem ausgezeichneten Küchenchef kochst du ein mehrgängiges Menü und lernst Techniken der gehobenen Küche für zu Hause.",
    durationMinutes: 210,
    price: 129,
    room: "Showküche",
    brandPartnerId: "sternekoch",
    imageSrc: "/course-images/kochen-showkueche.jpg",
    level: "Alle Level",
    maxParticipants: 12,
  },
  {
    slug: "naturkosmetik-workshop-dm",
    title: "Pflege-Workshop: Deine dm-Kosmetik, selbst gemacht",
    category: "beauty",
    shortDescription: "Eigene Cremes, Lippenbalsam und Badezusätze mit dm-Rohstoffen herstellen.",
    description:
      "In Kooperation mit dm mischst du deine eigene Naturkosmetik – von der Gesichtscreme bis zum Lippenbalsam. Alle Rohstoffe und Rezepturen werden gestellt, du nimmst deine Kreationen mit nach Hause.",
    durationMinutes: 90,
    price: 59,
    room: "Atelier 2",
    brandPartnerId: "dm",
    imageSrc: "/course-images/dm-workshop.jpg",
    level: "Einsteiger",
    maxParticipants: 12,
  },
  {
    slug: "rhode-glow-ritual",
    title: "Rhode Glow: Dein eigenes Skincare-Ritual",
    category: "beauty",
    shortDescription: "Minimalistische Pflegeroutine und eigene Lip-Case-Gestaltung mit rhode.",
    description:
      "Gemeinsam mit rhode entwickelst du eine reduzierte Skincare-Routine für deinen Hauttyp und gestaltest dein eigenes Lip-Case-Design – inspiriert von der minimalistischen rhode-Ästhetik.",
    durationMinutes: 90,
    price: 79,
    room: "Atelier 2",
    brandPartnerId: "rhode",
    imageSrc: "/course-images/rhode-produkte.jpg",
    level: "Alle Level",
    maxParticipants: 10,
  },
  {
    slug: "haus-labs-makeup-masterclass",
    title: "Make-up Masterclass: Dein Signature-Look mit Haus Labs",
    category: "beauty",
    shortDescription: "Foundation, Konturen und Pinseltechnik – professionelles Make-up mit Haus Labs.",
    description:
      "Mit Profi-Pinseln und Produkten von Haus Labs lernst du, Foundation passend zu deinem Hautton aufzutragen, Gesichtskonturen zu betonen und einen Look zu kreieren, der zu dir passt. Ein Make-up-Artist zeigt dir die wichtigsten Techniken Schritt für Schritt.",
    durationMinutes: 120,
    price: 99,
    room: "Atelier 2",
    brandPartnerId: "haus-labs",
    imageSrc: "/course-images/haus-labs-makeup.jpg",
    level: "Alle Level",
    maxParticipants: 10,
  },
  {
    slug: "blumenwerkstatt-tischdeko",
    title: "Blumenwerkstatt: Saisonale Tischarrangements",
    category: "floristik",
    shortDescription: "Üppige Arrangements mit Saisonblumen in Vintage-Gefäßen gestalten.",
    description:
      "Am großen Werktisch arrangierst du Rosen, Wicken und Wildblumen der Saison in Messing- und Glasgefäßen. Du lernst, Farben und Formen zu kombinieren, Blumen richtig anzuschneiden und eine stimmige Tischdeko für zu Hause zu gestalten.",
    durationMinutes: 150,
    price: 89,
    room: "Blumenwerkstatt",
    imageSrc: "/course-images/floristik-werkstatt.jpg",
    level: "Alle Level",
    maxParticipants: 8,
  },
  {
    slug: "fruehlingsstrauss-binden",
    title: "Frühlingsstrauß binden",
    category: "floristik",
    shortDescription: "Mit Tulpen, Ranunkeln und Anemonen deinen eigenen Handstrauß binden.",
    description:
      "Schritt für Schritt bindest du einen Strauß in Spiraltechnik: Blumen auswählen, Stiele vorbereiten, binden und schön verpacken. Den fertigen Strauß nimmst du mit nach Hause.",
    durationMinutes: 120,
    price: 69,
    room: "Blumenwerkstatt",
    imageSrc: "/course-images/floristik-strauss.jpg",
    level: "Einsteiger",
    maxParticipants: 10,
  },
  {
    slug: "weintasting-vom-fass",
    title: "Weintasting: Direkt vom Fass",
    category: "wein",
    shortDescription: "Rotweine direkt aus dem Barrique verkosten und Wein schmecken lernen.",
    description:
      "Gemeinsam mit einem Sommelier probierst du junge Rotweine direkt aus dem Holzfass und vergleichst sie mit fertig ausgebauten Jahrgängen. Du lernst, Wein richtig zu verkosten, Aromen zu erkennen und zu beschreiben – dazu gibt es Brot und Käse. Teilnahme ab 18 Jahren.",
    durationMinutes: 120,
    price: 79,
    room: "Showküche",
    imageSrc: "/course-images/weintasting.jpg",
    level: "Alle Level",
    maxParticipants: 14,
  },
];
