import { Course } from "./types";

export const courses: Course[] = [
  {
    slug: "zeichnen-fuer-einsteiger",
    title: "Zeichnen für Einsteiger",
    category: "zeichnen",
    shortDescription: "Grundlagen von Strich, Schraffur und Perspektive mit Faber-Castell-Material.",
    description:
      "In diesem Kurs lernst du die Grundtechniken des Zeichnens kennen: von der Strichführung über Schraffuren bis zur einfachen Perspektive. Alle Materialien von Faber-Castell werden gestellt.",
    durationMinutes: 120,
    price: 39,
    room: "Atelier 1",
    brandPartnerId: "faber-castell",
    level: "Einsteiger",
    maxParticipants: 12,
  },
  {
    slug: "urban-sketching",
    title: "Skizzieren im Park – Urban Sketching",
    category: "zeichnen",
    shortDescription: "Schnelles, lockeres Skizzieren von Alltagsszenen und Architektur.",
    description:
      "Wir ziehen los und skizzieren München: Architektur, Menschen, Straßenszenen. Ein Kurs für alle, die schnell und intuitiv zeichnen lernen wollen.",
    durationMinutes: 90,
    price: 35,
    room: "Treffpunkt Halle / Außenbereich",
    level: "Alle Level",
    maxParticipants: 10,
  },
  {
    slug: "aquarell-grundkurs",
    title: "Aquarellmalerei Grundkurs",
    category: "malen",
    shortDescription: "Farbmischung, Lasuren und Technik mit Faber-Castell-Aquarellfarben.",
    description:
      "Ein Einstieg in die Aquarellmalerei: Farbmischung, nass-in-nass Technik und erste kleine Kompositionen. Material von Faber-Castell inklusive.",
    durationMinutes: 150,
    price: 45,
    room: "Atelier 2",
    brandPartnerId: "faber-castell",
    level: "Einsteiger",
    maxParticipants: 10,
  },
  {
    slug: "koffer-kunst-rimowa",
    title: "Koffer-Kunst: Dein RIMOWA, dein Design",
    category: "malen",
    shortDescription: "Gestalte einen echten RIMOWA-Koffer mit deinem eigenen Design.",
    description:
      "In Kooperation mit RIMOWA gestaltest du einen echten Aluminium-Koffer nach deinen eigenen Vorstellungen – von abstrakten Mustern bis zum persönlichen Motiv. Der Koffer geht mit dir nach Hause.",
    durationMinutes: 120,
    price: 89,
    room: "Atelier 1",
    brandPartnerId: "rimowa",
    imageSrc: "/course-images/rimowa-koffer.jpg",
    level: "Alle Level",
    maxParticipants: 8,
  },
  {
    slug: "toepfern-scheibe",
    title: "Töpfern an der Scheibe",
    category: "toepfern",
    shortDescription: "Erste Gefäße an der Töpferscheibe formen.",
    description:
      "Du lernst den Umgang mit der Töpferscheibe und formst deine ersten eigenen Gefäße. Für Einsteiger geeignet, Brennen und Abholung im Anschluss möglich.",
    durationMinutes: 180,
    price: 55,
    room: "Werkraum Keramik",
    level: "Einsteiger",
    maxParticipants: 8,
  },
  {
    slug: "keramik-handaufbau",
    title: "Keramik-Handaufbau für Anfänger",
    category: "toepfern",
    shortDescription: "Gefäße ganz ohne Scheibe formen – mit Wulst- und Plattentechnik.",
    description:
      "Handaufbau-Techniken wie Wulst- und Plattentechnik eignen sich hervorragend für den Einstieg in die Keramik – ganz ohne Scheibe.",
    durationMinutes: 150,
    price: 49,
    room: "Werkraum Keramik",
    level: "Einsteiger",
    maxParticipants: 10,
  },
  {
    slug: "sticken-mit-stil",
    title: "Sticken mit Stil",
    category: "sticken",
    shortDescription: "Individuelle Stickmuster auf lululemon-Textilien gestalten.",
    description:
      "Gemeinsam mit lululemon gestaltest du individuelle Stickereien auf hochwertigen Sportbekleidungsstücken – von Monogrammen bis zu kleinen Icons.",
    durationMinutes: 120,
    price: 42,
    room: "Atelier 3",
    brandPartnerId: "lululemon",
    imageSrc: "/course-images/lululemon-sticken.jpg",
    level: "Alle Level",
    maxParticipants: 10,
  },
  {
    slug: "yoga-flow",
    title: "Yoga Flow",
    category: "yoga",
    shortDescription: "Dynamischer Vinyasa-Flow in Kooperation mit lululemon.",
    description:
      "Ein fließender Vinyasa-Flow für Körper und Geist, begleitet von lululemon mit Equipment und Kleidung zum Testen vor Ort.",
    durationMinutes: 75,
    price: 25,
    room: "Bewegungsraum",
    brandPartnerId: "lululemon",
    level: "Alle Level",
    maxParticipants: 16,
  },
  {
    slug: "steinhauen-grundlagen",
    title: "Steinhauen Grundlagen mit Profi-Werkzeug",
    category: "steinhauen",
    shortDescription: "Erste Schritte in der Steinbildhauerei mit Hilti-Werkzeug.",
    description:
      "Mit professionellem Hilti-Werkzeug lernst du die Grundlagen der Steinbearbeitung: Materialkunde, Sicherheit und erste einfache Formen.",
    durationMinutes: 180,
    price: 69,
    room: "Werkhalle",
    brandPartnerId: "hilti",
    level: "Einsteiger",
    maxParticipants: 6,
  },
  {
    slug: "rage-room",
    title: "Rage Room – Stress rauslassen",
    category: "rage-room",
    shortDescription: "Kontrolliert Dinge zertrümmern, um Dampf abzulassen.",
    description:
      "In Schutzausrüstung geht's rein: Geschirr, alte Elektronik und mehr werden mit Schlägern und Stangen zertrümmert. Ein Kurs zum Stressabbau.",
    durationMinutes: 45,
    price: 35,
    room: "Rage Room",
    level: "Alle Level",
    maxParticipants: 4,
  },
  {
    slug: "lasertag-arena",
    title: "Lasertag Arena",
    category: "lasertag",
    shortDescription: "Team-Action in der hauseigenen Lasertag-Arena.",
    description:
      "Zwei Teams, eine Arena, jede Menge Action. Perfekt für Gruppen, Teamevents oder einfach einen actionreichen Nachmittag.",
    durationMinutes: 60,
    price: 29,
    room: "Lasertag-Arena",
    level: "Alle Level",
    maxParticipants: 20,
  },
  {
    slug: "pilates-reformer",
    title: "Pilates Reformer Basics",
    category: "pilates",
    shortDescription: "Einstieg ins Reformer-Pilates für Kraft und Haltung.",
    description:
      "Ein Einsteigerkurs am Pilates-Reformer-Gerät: Kräftigung der Körpermitte, Haltungsverbesserung und Körperbewusstsein.",
    durationMinutes: 60,
    price: 28,
    room: "Bewegungsraum",
    level: "Einsteiger",
    maxParticipants: 10,
  },
  {
    slug: "sternekueche-zuhause",
    title: "Kochkurs: Sterneküche für Zuhause",
    category: "kochen",
    shortDescription: "Sterneküche zum Anfassen mit Chef Markus Reiter.",
    description:
      "Gemeinsam mit einem ausgezeichneten Küchenchef kochst du ein mehrgängiges Menü und lernst Techniken der gehobenen Küche für zu Hause.",
    durationMinutes: 210,
    price: 99,
    room: "Showküche",
    brandPartnerId: "sternekoch",
    level: "Alle Level",
    maxParticipants: 12,
  },
  {
    slug: "naturkosmetik-workshop-dm",
    title: "Pflege-Workshop: Deine dm-Kosmetik, selbst gemacht",
    category: "beauty",
    shortDescription: "Eigene Cremes, Lippenbalsam und Badezusätze mit dm-Rohstoffen herstellen.",
    description:
      "In Kooperation mit dm mischst du deine eigene Naturkosmetik – von der Gesichtscreme bis zum Lippenbalsam. Alle Rohstoffe und Rezepturen werden gestellt, du nimmst deine Kreationen mit nach Hause.",
    durationMinutes: 90,
    price: 39,
    room: "Atelier 2",
    brandPartnerId: "dm",
    level: "Einsteiger",
    maxParticipants: 12,
  },
  {
    slug: "rhode-glow-ritual",
    title: "Rhode Glow: Dein eigenes Skincare-Ritual",
    category: "beauty",
    shortDescription: "Minimalistische Pflegeroutine und eigene Lip-Case-Gestaltung mit rhode.",
    description:
      "Gemeinsam mit rhode entwickelst du eine reduzierte Skincare-Routine für deinen Hauttyp und gestaltest dein eigenes Lip-Case-Design – inspiriert von der minimalistischen rhode-Ästhetik.",
    durationMinutes: 90,
    price: 59,
    room: "Atelier 2",
    brandPartnerId: "rhode",
    level: "Alle Level",
    maxParticipants: 10,
  },
];
